# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hCl-ZVcbF1-B9r2gcRDNXPZLxVN0ozgK

# Analisis Sentimen Komentar Video YouTube

Analisis ini bertujuan untuk mengetahui distribusi sentimen (Positif, Netral, Negatif) dari komentar pada video YouTube berjudul  
“Generasi Muda, Bonus Demografi dan Masa Depan Indonesia” oleh Gibran Rakabuming.

Langkah-langkahnya meliputi:
- Import library yang dibutuhkan
- Membaca data komentar dari file Excel
- Melakukan preprocessing data
- Menghitung jumlah komentar berdasarkan kategori sentimen
- Membuat visualisasi grafik batang untuk memudahkan interpretasi hasil

---

**Catatan:** Data komentar sudah diklasifikasikan sentimennya sebelumnya dan tersimpan di dataframe `sentimen_count`.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

try:
    from scripts.comment_loader import load_comment_dataframe
except ModuleNotFoundError:
    from comment_loader import load_comment_dataframe

"""## Membaca Data dan Preprocessing

Data komentar yang berisi username dan komentar dibaca dari file Excel. Karena file tidak memiliki header,  
penentuan kolom dilakukan secara manual. Selanjutnya, dilakukan preprocessing sederhana jika diperlukan, misalnya menghapus baris kosong atau duplikat (tidak ada pada contoh ini).

"""

data = Path(__file__).resolve().parents[1] / "data" / "Youtube_Comment_Gibran.xlsx"
df = load_comment_dataframe(data)

"""## Analisis Sentimen dengan VADER
Pada langkah ini, kita menggunakan VADER (Valence Aware Dictionary and sEntiment Reasoner), sebuah alat analisis sentimen berbasis lexicon dan rule-based yang khusus dirancang untuk analisis sentimen teks pendek seperti komentar media sosial.

Fungsi analisis_sentimen(teks) menerima input berupa teks komentar, lalu menghitung skor sentimen menggunakan metode polarity_scores dari VADER. Skor utama yang digunakan adalah nilai compound yang merupakan skor sentimen keseluruhan dalam rentang -1 (sangat negatif) sampai +1 (sangat positif).

Klasifikasi sentimen dilakukan berdasarkan nilai compound:

Positif jika nilai ≥ 0.05

Negatif jika nilai ≤ -0.05

Netral jika nilai di antara -0.05 dan 0.05

Setelah proses ini, kolom baru 'Sentimen' ditambahkan ke dataframe yang berisi kategori sentimen untuk setiap komentar. Data hasil analisis ini disimpan kembali ke file Excel komentar_dengan_sentimen.xlsx untuk digunakan pada tahap analisis berikutnya.


"""

analyzer = SentimentIntensityAnalyzer()

def analisis_sentimen(teks):
    skor = analyzer.polarity_scores(str(teks))
    nilai = skor['compound']
    if nilai >= 0.05:
        return "Positif"
    elif nilai <= -0.05:
        return "Negatif"
    else:
        return "Netral"

df['Sentimen'] = df['Komentar'].apply(analisis_sentimen)
df.to_excel("komentar_dengan_sentimen.xlsx", index=False)

sentimen_count = df['Sentimen'].value_counts().reset_index()
sentimen_count.columns = ['Sentimen', 'Jumlah']

"""## Visualisasi Grafik Batang Sentimen Komentar

Visualisasi menggunakan seaborn dan matplotlib untuk menghasilkan grafik batang profesional.  
Warna disesuaikan agar mudah dibaca dan mencerminkan kategori sentimen.  
Tiap batang diberi label jumlah komentar dan total komentar ditampilkan di atas grafik.
"""

import seaborn as sns
import matplotlib.pyplot as plt

total_komentar = sentimen_count['Jumlah'].sum()

sns.set(style="whitegrid")
plt.figure(figsize=(9, 6))

warna = {'Positif': '#27ae60', 'Netral': '#f39c12', 'Negatif': '#c0392b'}

bar = sns.barplot(
    data=sentimen_count,
    x='Sentimen',
    y='Jumlah',
    hue='Sentimen',
    palette=warna,
    edgecolor='black',
    linewidth=1,
    dodge=False
)

for index, row in sentimen_count.iterrows():
    bar.text(
        index,
        row.Jumlah + max(sentimen_count['Jumlah']) * 0.02,
        f"{row.Jumlah:,}",
        color='black',
        ha="center",
        fontweight='bold',
        fontsize=11
    )

plt.text(
    x=1.05,
    y=max(sentimen_count['Jumlah']) * 1.1,
    s=f"Total Komentar: {total_komentar:,}",
    ha='right',
    fontsize=12,
    fontweight='semibold',
    color='#2c3e50'
)

plt.title(
    "Analisis Sentimen Komentar pada Video Youtube\n“Generasi Muda, Bonus Demografi dan Masa Depan Indonesia”\noleh Gibran Rakabuming",
    fontsize=12, fontweight='semibold', color='#34495e', pad=56
)
plt.xlabel("Kategori Sentimen", fontsize=14, fontweight='medium', color='#34495e')
plt.ylabel("Jumlah Komentar", fontsize=14, fontweight='medium', color='#34495e')

plt.grid(axis='y', linestyle='--', linewidth=0.7, alpha=0.7)
sns.despine(top=True, right=True)
plt.ylim(0, max(sentimen_count['Jumlah']) * 1.2)

plt.tight_layout()

plt.subplots_adjust(top=0.85)

plt.savefig("grafik_sentimen_batang_profesional.png", dpi=300)
plt.show()
